version: '3.7'
services:
  currency-exchange:
    image: in28min/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    environment:
       EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server

  currency-conversion:
    image: in28min/currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server

  naming-server:
    image: in28min/naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  api-gateway:
    image: in28min/api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network

networks:
  currency-network: